### ISSUE TITLE
Not able to debug any test Getting unauthorised error "wwwAuthenticate NTLM" 

### ISSUE THREAD

**Issue by babula38** [Microsoft/IIS.Administration#164]
### Steps to reproduce the issue:- 

Open the same code base in two instance of visual studio. In one instance run the application with ctrl+F5.
now go to the other instance open any test, put a break point try to debug.

Expected Result:- Test should run properly without any error.

Actual Result:-   unauthorised error Utils class GetApiKey method.

### Note:- Please let me know if I have to do any configuration changes for this.

**Comment by jimmyca15** [comment]
Are you running both instances as an administrator?

**Comment by babula38** [comment]
Yes both instance are running under Administrator role.
First instance is running "start without debugging" mode
second instance is in "debug mode" putting break point in any test.

Hi if you want me I can record my screen and send you the link which might help you further.

just let me know if you want that.

![github1](https://user-images.githubusercontent.com/4153708/31947892-063a12cc-b8f3-11e7-8c89-f502c0841e71.PNG)

**Comment by jimmyca15** [comment]
You are able to create access tokens through the API Explorer?

**Comment by babula38** [comment]
Yes I am able to create the access token through the API explorer.
It is not a specific test which gives the error, pick any test and run it in debug mode.
Please find the stack trace below:-

   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
   at Microsoft.IIS.Administration.Tests.Utils.GetApiKey(String serverUri, HttpClient client) in D:\SourceCode\IIS.Administration-dev\test\Microsoft.IIS.Administration.Tests\Utils.cs:line 30
   at Microsoft.IIS.Administration.Tests.ApiHttpClient.Init(String serverUri) in D:\SourceCode\IIS.Administration-dev\test\Microsoft.IIS.Administration.Tests\ApiHttpClient.cs:line 38
   at Microsoft.IIS.Administration.Tests.ApiHttpClient..ctor(String serverUri, HttpMessageHandler handler, Boolean disposeHandler) in D:\SourceCode\IIS.Administration-dev\test\Microsoft.IIS.Administration.Tests\ApiHttpClient.cs:line 32
   at Microsoft.IIS.Administration.Tests.ApiHttpClient.Create(String serverUri) in D:\SourceCode\IIS.Administration-dev\test\Microsoft.IIS.Administration.Tests\ApiHttpClient.cs:line 27
   at Microsoft.IIS.Administration.Tests.ApiHttpClient.Create() in D:\SourceCode\IIS.Administration-dev\test\Microsoft.IIS.Administration.Tests\ApiHttpClient.cs:line 17
   at Microsoft.IIS.Administration.Tests.Api.CanCommunicate(Int32 runCount) in D:\SourceCode\IIS.Administration-dev\test\Microsoft.IIS.Administration.Tests\Api.cs:line 19

**Comment by jimmyca15** [comment]
I cloned the repo and ran tests to see if I got the same issue but I was able to recreate the keys as expected. The big points here are 
 * Running the dev environment setup script.
 * Making sure that the test.config.json points to the port the application is running on.
 * Making sure the Windows identity being used to execute the tests is capable of creating access keys.

**Comment by babula38** [comment]
@jimmyca15 thanks for the feed back, now it is working fine. The issue here was with user permission.Missed to add the current user which I use to execute Test, in "administrators" section of config file.
