### ISSUE TITLE
appveyor CI fails at monitoring.cs:221

### ISSUE THREAD

**Issue by bariscaglar** [Microsoft/IIS.Administration#194]
at Microsoft.IIS.Administration.Tests.Monitoring.<ManySites>d__6.MoveNext() in c:\src\repos\IIS.Administration\test\Microsoft.IIS.Administration.Tests\Monitoring.cs:line 221
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

**Comment by bariscaglar** [comment]
Here is the monitoring info. The test fails because total bytes sent is 0:

Created 20 sites
Waiting for all site processes to start
Validating webserver monitoring data
{
  "id": "ahJEWSUwbzgeCFbGtgmP9A",
  "network": {
    "bytes_sent_sec": 0,
    "bytes_recv_sec": 274,
    "connection_attempts_sec": 2,
    "total_bytes_sent": 0,
    "total_bytes_recv": 1746,
    "total_connection_attempts": 18,
    "current_connections": 18
  },
  "requests": {
    "active": 20,
    "per_sec": 2,
    "total": 18
  },
  "memory": {
    "handles": 7613,
    "private_bytes": 934121472,
    "private_working_set": 219430912,
    "system_in_use": 1478025216,
    "installed": 2498781184
  },
  "cpu": {
    "threads": 400,
    "processes": 20,
    "percent_usage": 11,
    "system_percent_usage": 59
  },
  "disk": {
    "io_write_operations_sec": 15,
    "io_read_operations_sec": 565,
    "page_faults_sec": 1584
  },
  "cache": {
    "file_cache_count": 0,
    "file_cache_memory_usage": 0,
    "file_cache_hits": 0,
    "file_cache_misses": 0,
    "total_files_cached": 0,
    "output_cache_count": 0,
    "output_cache_memory_usage": 0,
    "output_cache_hits": 0,
    "output_cache_misses": 0,
    "uri_cache_count": 0,
    "uri_cache_hits": 0,
    "uri_cache_misses": 20,
    "total_uris_cached": 0
  },
  "_links": {
    "self": {
      "href": "/api/webserver/monitoring/ahJEWSUwbzgeCFbGtgmP9A"
    }
  }
}

**Comment by bariscaglar** [comment]
@jimmyca15 why do we require "total_bytes"sent" to be greater than 0?

**Comment by bariscaglar** [comment]
It might be a warmup issue; perhaps the sites have not started sending data back yet.

**Comment by bariscaglar** [comment]
Fixed by #195
