### ISSUE TITLE
Launching the application as application (instead of service) prevents IIS.Administration from getting w3svc's status

### ISSUE THREAD

**Issue by shhsu** [microsoft/IIS.Administration#241]
`ServiceController.GetServices()` throws exception.

```
Microsoft IIS Administration API encountered an unexpected error: System.PlatformNotSupportedException: ServiceController enables manipulating and accessing Windows services and it is not applicable for other operating systems.
   at System.ServiceProcess.ServiceController.GetServices()
   at Microsoft.IIS.Administration.WebServer.Info.InfoHelper.GetService() in D:\GitHub\Microsoft\IIS.Administration\src\Microsoft.IIS.Administration.WebServer.Info\InfoHelper.cs:line 89
   at Microsoft.IIS.Administration.WebServer.Info.InfoHelper.GetStatus() in D:\GitHub\Microsoft\IIS.Administration\src\Microsoft.IIS.Administration.WebServer.Info\InfoHelper.cs:line 21
   at Microsoft.IIS.Administration.WebServer.Info.InfoHelper.ToJsonModel(IWebServerVersion versionProvider) in D:\GitHub\Microsoft\IIS.Administration\src\Microsoft.IIS.Administration.WebServer.Info\InfoHelper.cs:line 52
   at Microsoft.IIS.Administration.WebServer.Info.WebServerInfoController.Get() in D:\GitHub\Microsoft\IIS.Administration\src\Microsoft.IIS.Administration.WebServer.Info\controllers\WebServerInfoController.cs:line 26
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.IIS.Administration.WebServer.Injector.ProceedNoTransaction(HttpContext context) in D:\GitHub\Microsoft\IIS.Administration\src\Microsoft.IIS.Administration.WebServer\Middleware\Injector.cs:line 73
   at Microsoft.IIS.Administration.WebServer.Injector.Invoke(HttpContext context) in D:\GitHub\Microsoft\IIS.Administration\src\Microsoft.IIS.Administration.WebServer\Middleware\Injector.cs:line 35
   at Microsoft.IIS.Administration.HeadTransform.Invoke(HttpContext context) in D:\GitHub\Microsoft\IIS.Administration\src\Microsoft.IIS.Administration\HeadTransform.cs:line 56
   at Microsoft.IIS.Administration.Startup.<>c.<<Configure>b__4_0>d.MoveNext() in D:\GitHub\Microsoft\IIS.Administration\src\Microsoft.IIS.Administration\Startup.cs:line 175
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.IIS.Administration.Security.Authorization.AuthorizationPolicyMiddleware.Invoke(HttpContext context, IAuthorizationService authorizationService) in D:\GitHub\Microsoft\IIS.Administration\src\Microsoft.IIS.Administration\Security\Authorization\AuthorizationPolicyMiddleware.cs:line 27
   at Microsoft.IIS.Administration.Security.WindowsAuthenticationExtensions.<>c.<<UseWindowsAuthentication>b__0_0>d.MoveNext() in D:\GitHub\Microsoft\IIS.Administration\src\Microsoft.IIS.Administration\Security\WindowsAuthentication.cs:line 35
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.IIS.Administration.Cors.CorsExtensions.<>c.<<UseCrossOrigin>b__0_2>d.MoveNext() in D:\GitHub\Microsoft\IIS.Administration\src\Microsoft.IIS.Administration\Cors\CorsExtensions.cs:line 74
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at Microsoft.IIS.Administration.Cors.CorsExtensions.<>c__DisplayClass0_0.<<UseCrossOrigin>b__0>d.MoveNext() in D:\GitHub\Microsoft\IIS.Administration\src\Microsoft.IIS.Administration\Cors\CorsExtensions.cs:line 35
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.IIS.Administration.ErrorHandler.Invoke(HttpContext context) in D:\GitHub\Microsoft\IIS.Administration\src\Microsoft.IIS.Administration\Errors\ErrorHandler.cs:line 28
```

**Comment by yaqiyang** [comment]
Closed. New features are not going to be implemented in the near future
