### ISSUE TITLE
Bug with manage.iis.net's interface

### ISSUE THREAD

**Issue by StephenShamakian** [Microsoft/IIS.Administration#25]
When testing out the https://manage.iis.net interface it is only showing one website when the server and the API report multiple.

API Output:
![issue1](https://cloud.githubusercontent.com/assets/6382844/19349991/f54a3f84-9123-11e6-9268-78c064da40ed.PNG)

Interface Output:
![issue2](https://cloud.githubusercontent.com/assets/6382844/19350050/323ec4be-9124-11e6-987d-9cb9bfcccfcd.PNG)

**Comment by jimmyca15** [comment]
What browser was this running in? Is there an error being displayed in the developer console (F12)?

**Comment by jimmyca15** [comment]
@RedTechie 

What browser was this running in? Is there an error being displayed in the developer console (F12)?

**Comment by simplespirit** [comment]
I also only see the default site in both IE11 and Chrome. In the Console for Chrome I get:

Uncaught SyntaxError: Unexpected end of JSON input(anonymous function) @ content.js:7

**Comment by jimmyca15** [comment]
![image](https://cloud.githubusercontent.com/assets/21000428/19364619/bec6124c-9143-11e6-8da3-8fd7575bd5d8.png)

Can you try clearing the cache and reloading? The easiest way is to check the "Disable cache" box as shown in the picture.

**Comment by simplespirit** [comment]
Done. Same error in Chrome. FWIW I get no console errors in IE but still only see the default site. When I go to App Pools I see the entire list.

[cid:image002.jpg@01D2256A.E4A3D930]

**Comment by RedTechie** [comment]
I'm not by my workstation ATM. But I was using Firefox when I experienced the issue. I used firebug to dig deeper and I did not see any errors in the console. 

I also noticed that the jason results returned from the API in firebug was only returning one website. So it may be a bug with the API... But in the API explorer it was returning fine.

**Comment by simplespirit** [comment]
I also only see one response in the JSON using fiddler.

**Comment by jimmyca15** [comment]
The fact that the websites are showing up in the API Explorer is a good sign because the it is making AJAX requests to the API just like manage.iis.net. Somehow the ajax request from manage.iis.net is getting cut short.

**Comment by jimmyca15** [comment]
Similar behavior has happened before that was being caused by an exception happening during the serialization of the response. If this is the case then the exception should appear in the API's logs. If you look in 
C:\Program Files\IIS Administration\1.0.36\Microsoft.IIS.Administration\logs
If there has been any exceptions there should be a log file with a name similar to log-20161004.txt. Would you mind attaching that if it exists?

**Comment by RedTechie** [comment]
Yup there are some stack traces!

2016-10-13 18:15:02.814 -04:00 [Error] Connection id ""0HKVHSNFKM4SU"": An unhandled exception was thrown by the application.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.IIS.Administration.WebServer.Sites.SiteHelper.ToJsonModel(Binding binding)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeDictionary(JsonWriter writer, IDictionary values, JsonDictionaryContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Microsoft.AspNetCore.Mvc.Formatters.JsonOutputFormatter.WriteObject(TextWriter writer, Object value)
   at Microsoft.AspNetCore.Mvc.Formatters.JsonOutputFormatter.<WriteResponseBodyAsync>d__9.MoveNext()


2016-10-13 18:15:02.876 -04:00 [Error] Object reference not set to an instance of an object.
	   at Microsoft.IIS.Administration.WebServer.Sites.SiteHelper.ToJsonModel(Binding binding)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeDictionary(JsonWriter writer, IDictionary values, JsonDictionaryContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Microsoft.AspNetCore.Mvc.Formatters.JsonOutputFormatter.WriteObject(TextWriter writer, Object value)
   at Microsoft.AspNetCore.Mvc.Formatters.JsonOutputFormatter.<WriteResponseBodyAsync>d__9.MoveNext()

**Comment by jimmyca15** [comment]
Awesome, thank you so much for that. The stack trace tells us that there is a problem retrieving the bindings for the website.

**Comment by jimmyca15** [comment]
What is the bindings setup for your second website?

**Comment by jimmyca15** [comment]
I was able to reproduce this issue. If you create an https binding for a website that does not have a valid certificate mapped to the chosen port then this error will occur. If you create the site through the API there shouldn't be a way to get into this state. 

Did you create these sites through the API/manage.iis.net or some other method?

**Solution**
Change the binding from HTTPS to HTTP. Then through the API, manage.iis.net, or INetMgr change the binding to HTTPS and pick a certificate to use.

**Comment by RedTechie** [comment]
Looking into this. But at first glance all of the certs are valid when viewed through Inetmgr. The bindings were created using Inetmgr. I have not tired creating any sites or objects using the API as of yet.

One thing that does seem to be consistent is it's only affecting the sites with SSL bindings.

**Comment by jimmyca15** [comment]
https://SERVERIP:55539/api/webserver/websites?fields=name,status,physical_path,bindings,application_pool queries all sites from the API and requests that the listed fields of the sites be displayed. The application_pool data isn't going to be displayed if this bug is occurring because the bug is terminating the JSON response.

**Comment by jimmyca15** [comment]
Also are the certificates on a Central Cert Store?

**Comment by RedTechie** [comment]
Ah That would make sense! As it falls in line with what I just found out! I had to remove the below non-http/https bindings from the one site that was working:
![issue3](https://cloud.githubusercontent.com/assets/6382844/19371508/97c85e0a-9181-11e6-88a4-bc94c2025349.PNG)

After removing those all the rest of the sites appeared! I don't know why but we see those bindings appear randomly on our servers. Any idea why or what causes them?

**Comment by jimmyca15** [comment]
Thank you again. There was actually multiple issues at play here. I found one and you have found another. Those bindings appear on the default web site if you have certain optional windows features enabled. For example. Unfortunately we did not take into account other activation mechanisms and if those bindings are present then this error will occur.

![image](https://cloud.githubusercontent.com/assets/21000428/19371718/45643ac4-916a-11e6-8024-c42e9d215c37.png)

**Comment by RedTechie** [comment]
No problem! Glad to help out! Been waiting anxiously for the API :D Super excited it's in preview!

So I don't seem to have those options (This is on a 2008 R2 server):
![issue4](https://cloud.githubusercontent.com/assets/6382844/19372008/0d6d1d40-9186-11e6-889e-73a420cd6a00.PNG)

**Comment by jimmyca15** [comment]
In your case "non http activation" should be the cause of **net.tcp** bindings appearing. They are there even when it is off?

**Comment by RedTechie** [comment]
Yup, we randomly see them appear on some servers occasionally. We thought it was something to do with .NET re-registering itself or something but weren't exactly sure why we would randomly see them appear.

**Comment by simplespirit** [comment]
I suspect my experience is the same issue. I built an app to allow our devs to proxy app pool cycling and noticed those weird mappings on one of the sites. I'm using the web.admin class and not json so it wasn't an issue and I just filtered out the odd bindings.

Get Outlook for iOS<https://aka.ms/o0ukef>




On Thu, Oct 13, 2016 at 9:35 PM -0400, "RedTechie" <notifications@github.com<mailto:notifications@github.com>> wrote:


Yup, we randomly see them appear on some servers occasionally. We thought it was something to do with .NET re-registering itself or something but weren't exactly sure why we would randomly see them appear.

-

**Comment by simplespirit** [comment]
Removed the odd bindings from my default site and now every other site appears as expected. Thanks!

**Comment by shirhatti** [comment]
Linking related issues to follow their status:
- https://github.com/aspnet/Mvc/issues/5413
- https://github.com/aspnet/IISIntegration/issues/39

**Comment by jimmyca15** [comment]
Re opening this issue until we release the updated API.

**Comment by jimmyca15** [comment]
Release is live, available at https://manage.iis.net/get. The GUI has been updated as well.
