### ISSUE TITLE
HTTP/1.1 500 Internal Server Error with UTC <> UTC 00

### ISSUE THREAD

**Issue by PNL-O** [Microsoft/IIS.Administration#329]
Hi,

I am located in the Pacific the timezone is UTC-10 All our servers are configured on this timezone to be able to easily use the logs.
I need to use the IIS administration API to monitor IIS services.
If I set the timezone to UTC it works, if it is UTC-10 I get error 500.
Is it possible to correct the code to resolve the problem?

Thanks.

Best regards

Patrick

The error in eventviewer : 
_Log Name:      Application
Source:        Microsoft IIS Administration API
Date:          10/17/2024 2:45:28 AM
Event ID:      1
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      in-mssqls1-ivw.opt.intranet
Description:
Category: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware
EventId: 1
RequestId: 80000027-0001-f900-b63f-84710c7967bb
RequestPath: /api/webserver/application-pools

An unhandled exception has occurred while executing the request.

Exception: 
System.ArgumentOutOfRangeException: The UTC time represented when the offset is applied must be between year 0 and 10,000. (Parameter 'offset')
   at System.DateTimeOffset.ValidateDate(DateTime dateTime, TimeSpan offset)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authorization.Policy.PolicyEvaluator.AuthenticateAsync(AuthorizationPolicy policy, HttpContext context)
   at Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter.OnAuthorizationAsync(AuthorizationFilterContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.IIS.Administration.WebServer.Injector.ProceedNoTransaction(HttpContext context)
   at Microsoft.IIS.Administration.WebServer.Injector.Invoke(HttpContext context)
   at Microsoft.IIS.Administration.HeadTransform.Invoke(HttpContext context)
   at Microsoft.IIS.Administration.Startup.<>c.<<Configure>b__4_0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.IIS.Administration.Security.Authorization.AuthorizationPolicyMiddleware.Invoke(HttpContext context, IAuthorizationService authorizationService)
   at Microsoft.IIS.Administration.Security.WindowsAuthenticationExtensions.<>c.<<UseWindowsAuthentication>b__0_0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.IIS.Administration.Cors.CorsExtensions.<>c.<<UseCrossOrigin>b__0_2>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.IIS.Administration.Cors.CorsExtensions.<>c__DisplayClass0_0.<<UseCrossOrigin>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.IIS.Administration.ErrorHandler.Invoke(HttpContext context)
   at Microsoft.IIS.Administration.ErrorHandler.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Microsoft IIS Administration API" />
    <EventID Qualifiers="0">1</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2024-10-17T02:45:28.827568700Z" />
    <EventRecordID>733190</EventRecordID>
    <Channel>Application</Channel>
    <Computer>in-mssqls1-ivw.opt.intranet</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Category: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware
EventId: 1
RequestId: 80000027-0001-f900-b63f-84710c7967bb
RequestPath: /api/webserver/application-pools

An unhandled exception has occurred while executing the request.

Exception: 
System.ArgumentOutOfRangeException: The UTC time represented when the offset is applied must be between year 0 and 10,000. (Parameter 'offset')
   at System.DateTimeOffset.ValidateDate(DateTime dateTime, TimeSpan offset)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authorization.Policy.PolicyEvaluator.AuthenticateAsync(AuthorizationPolicy policy, HttpContext context)
   at Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter.OnAuthorizationAsync(AuthorizationFilterContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.&lt;InvokeFilterPipelineAsync&gt;g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.&lt;InvokeAsync&gt;g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.&lt;InvokeAsync&gt;g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.IIS.Administration.WebServer.Injector.ProceedNoTransaction(HttpContext context)
   at Microsoft.IIS.Administration.WebServer.Injector.Invoke(HttpContext context)
   at Microsoft.IIS.Administration.HeadTransform.Invoke(HttpContext context)
   at Microsoft.IIS.Administration.Startup.&lt;&gt;c.&lt;&lt;Configure&gt;b__4_0&gt;d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.IIS.Administration.Security.Authorization.AuthorizationPolicyMiddleware.Invoke(HttpContext context, IAuthorizationService authorizationService)
   at Microsoft.IIS.Administration.Security.WindowsAuthenticationExtensions.&lt;&gt;c.&lt;&lt;UseWindowsAuthentication&gt;b__0_0&gt;d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.IIS.Administration.Cors.CorsExtensions.&lt;&gt;c.&lt;&lt;UseCrossOrigin&gt;b__0_2&gt;d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.IIS.Administration.Cors.CorsExtensions.&lt;&gt;c__DisplayClass0_0.&lt;&lt;UseCrossOrigin&gt;b__0&gt;d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.IIS.Administration.ErrorHandler.Invoke(HttpContext context)
   at Microsoft.IIS.Administration.ErrorHandler.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.&lt;Invoke&gt;g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
</Data>
  </EventData>
</Event>_

**Comment by PNL-O** [comment]
Hi, 
In addition to version 2.3.0 of IIS Administration, it works perfectly in UTC-10.
It's really weird because I imagine that the developers' systems located in the USA have a UTC other than 00.

Best regards
Patrick
